### ISSUE TITLE
Fail to detect the phpunit path if composer `bin-dir` config is used

### ISSUE THREAD

**Issue by Spy-Seth** [spatie/phpunit-watcher#61] opened 2018-03-21 10:40 UTC
It seems that `phpunit-watcher` is failling to detect the phpunit path when composer is configured to move the binaries outside the `vendor` directory:
```json
"config": {
  "bin-dir": "bin"
}
```

The `phpunit-watcher` will output:

```
sh: vendor/bin/phpunit: No such file or directory
```

It could be a good idea to use the `config.bin-dir` value to determine the composer binary direcotry path

**Comment by romainnorberg** [comment] 2018-07-17 09:41
Duplicate of #66 ?

**Comment by freekmurze** [comment] 2018-07-17 15:53
Duplicate of #66 indeed

**Closed by freekmurze** 2018-07-17 15:53 UTC
