### ISSUE TITLE
combine arguments with default arguments

### ISSUE THREAD

**Issue by anurat** [spatie/phpunit-watcher#131] opened 2021-01-21 09:20 UTC
I see that currently the initial arguments will be replaced with arguments provided.

> When starting the tool with some arguments (eg phpunit-watcher watch --filter=my_favourite_test) those arguments will get used instead of the ones specified in the config file.

However it will be useful to have default arguments which do not get replaced by provided arguments.
For example if we have 
```
phpunit:
  default_arguments: '--stop-on-failure'
```
and provide some more arguments (phpunit-watcher watch --filter=some_test)
then both arguments are used.

I use --filter quite often and would love it not to replace the default arguments.

**Comment by iandunn** [comment] 2021-05-06 15:00
This looks like a duplicate of #129

**Closed** 2021-09-07 10:03 UTC
